import Head from "next/head";
import { Landing_page } from "../src/landing_page";
import { motion, AnimateSharedLayout, AnimatePresence } from "framer-motion";

export default function Home() {
    return (
        <AnimatePresence>
            <Head>
                <title>Victor</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Landing_page />
        </AnimatePresence>
    );
}
